countries:
  - code: KE
    name: Kenya
    live: true
    team_name: Chancen Kenya team
    escalation_contact: support.ke@chancen.org
    privacy_url: /privacy/ke
    terms_url: /terms/ke
    isa_content_source: kenya
  - code: RW
    name: Rwanda
    live: true
    team_name: Chancen Rwanda team
    escalation_contact: support.rw@chancen.org
    privacy_url: /privacy/rw
    terms_url: /terms/rw
    isa_content_source: rwanda
  - code: ZA
    name: South Africa
    live: true
    team_name: Chancen South Africa team
    escalation_contact: support.za@chancen.org
    privacy_url: /privacy/za
    terms_url: /terms/za
    isa_content_source: south_africa
  - code: GH
    name: Ghana
    live: true
    team_name: Chancen team
    escalation_contact: support@chancen.org
    privacy_url: /privacy/gh
    terms_url: /terms/gh
    isa_content_source: general
